# Generated by Django 4.0.5 on 2022-06-10 02:05

from django.db import migrations

def populate_sections(apps, schemaeditor):
    sections = {
        "Sport": "Sport section...",
        "Social": "Social section...",
        "Entertainment": "Entertainment section..."
    }
    #name app , name model
    Section = apps.get_model('articles', 'Section')
    for name, desc in sections.items():
        section_obj = Section(name=name, description=desc)
        section_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_sections),
    ]
